---
- hosts: localhost
  vars:
    src_dir: "/usr/local/src/emacs"
    pkgs_dir: "/usr/local/pkgs"
    install_dir: "{{ pkgs_dir }}/emacs"
    lib_dir: "{{ install_dir }}/emacs-pkgs"

  tasks:
    - name: "emacs: cloning"
      git:
        repo: https://git.savannah.gnu.org/git/emacs.git
        dest: "{{ src_dir }}"
        clone: true

    - name: "emacs: autogen"
      command:
        argv:
          - "./autogen.sh"
        chdir: "{{ src_dir }}"
        creates: "{{ src_dir }}/configure"

    - name: "emacs: configure"
      command:
        argv:
          - ./configure
          - --prefix={{ install_dir }}
          - --with-json
          - --with-tree-sitter
          - --with-pgtk
          - --without-gsettings
          - --with-xinput2
          - --with-file-notification=yes
          - --without-compress-install
          - --with-native-compilation=aot
        chdir: "{{ src_dir }}"

    - name: "emacs: make"
      community.general.make:
        chdir: "{{ src_dir }}"

    - name: "emacs: install"
      community.general.make:
        chdir: "{{ src_dir }}"
        target: install

    - name: "emacs: stow"
      command: "stow emacs"
      args:
        chdir: "{{ pkgs_dir }}"

    - name: "emacs: install lisp packages"
      loop:
        - name: org-modern
          repo: https://github.com/minad/org-modern.git
        - name: pulsar
          repo: https://github.com/protesilaos/pulsar.git
      git:
        repo: "{{ item.repo }}"
        dest: "{{ lib_dir }}/{{ item.name }}"
        clone: true
